In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
### One hot representation
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2678, 7583, 9289, 6458],
 [2678, 7583, 9289, 9151],
 [2678, 5321, 9289, 8688],
 [2164, 9185, 4042, 8529, 5796],
 [2164, 9185, 4042, 8529, 456],
 [453, 2678, 4724, 9289, 1844],
 [5458, 237, 9930, 8529]]

In [6]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2678 7583 9289 6458]
 [   0    0    0    0 2678 7583 9289 9151]
 [   0    0    0    0 2678 5321 9289 8688]
 [   0    0    0 2164 9185 4042 8529 5796]
 [   0    0    0 2164 9185 4042 8529  456]
 [   0    0    0  453 2678 4724 9289 1844]
 [   0    0    0    0 5458  237 9930 8529]]


In [9]:
## feature representation
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 191ms/step


array([[[-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828,
         -0.02339131,  0.00980952,  0.0396759 , -0.04621765,
          0.00918505, -0.00790824],
        [-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828,
         -0.02339131,  0.00980952,  0.0396759 , -0.04621765,
          0.00918505, -0.00790824],
        [-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828,
         -0.02339131,  0.00980952,  0.0396759 , -0.04621765,
          0.00918505, -0.00790824],
        [-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828,
         -0.02339131,  0.00980952,  0.0396759 , -0.04621765,
          0.00918505, -0.00790824],
        [-0.02997169,  0.02849989, -0.04933215,  0.00906875,
         -0.0358493 ,  0.00816835, -0.04075551, -0.04157526,
         -0.04281043, -0.04660757],
        [-0.04160517, -0.03195646,  0.02588472, -0.01169718,
         -0.04768395, -0.01997662, -0.01044737, -0.03369387,
          0.03602457,  0.00033092],
        [ 0.0313308 ,  0.00699038,  0.04544475, -0.0

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 41ms/step


array([[-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828, -0.02339131,
         0.00980952,  0.0396759 , -0.04621765,  0.00918505, -0.00790824],
       [-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828, -0.02339131,
         0.00980952,  0.0396759 , -0.04621765,  0.00918505, -0.00790824],
       [-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828, -0.02339131,
         0.00980952,  0.0396759 , -0.04621765,  0.00918505, -0.00790824],
       [-0.03167091,  0.0271186 , -0.0454193 ,  0.02284828, -0.02339131,
         0.00980952,  0.0396759 , -0.04621765,  0.00918505, -0.00790824],
       [-0.02997169,  0.02849989, -0.04933215,  0.00906875, -0.0358493 ,
         0.00816835, -0.04075551, -0.04157526, -0.04281043, -0.04660757],
       [-0.04160517, -0.03195646,  0.02588472, -0.01169718, -0.04768395,
        -0.01997662, -0.01044737, -0.03369387,  0.03602457,  0.00033092],
       [ 0.0313308 ,  0.00699038,  0.04544475, -0.0361042 , -0.01325075,
        -0.03649161, -0.04376352, -0.02349055